# Generated by Django 2.1.1 on 2018-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20181104_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
