# Generated by Django 2.1.1 on 2018-11-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_profile_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
